name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev python3-pip build-essential git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install Cython==0.29.36 virtualenv
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Check for APK
      run: ls -l bin/*.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: QRify-APK
        path: bin/*.apk
